version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-app
    container_name: react-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:8080/api
