export const SOURCES = ["BBC News", "The Guardian", "New York Times"];

export const CATEGORIES = [
  "Stage",
  "Australia News",
  "Life and Style",
  "Football",
  "Money",
  "Politics",
  "Technology",
  "Sports",
  "Books",
  "Opinion",
  "Crosswords",
  "News",
  "Television & Radio",
  "Law",
  "Film",
  "World News",
  "Art and Design",
  "US news",
  "The Filter",
  "Music",
  "Magazine",
  "New",
  "General",
  "Well",
  "Health",
  "Style",
  "Real Estate",
  "Art",
  "Job",
];
